# Generated by Django 4.2 on 2023-06-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realcam', '0002_alter_camera_url_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='warning_images'),
        ),
    ]
