# Generated by Django 4.2 on 2023-04-18 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userMember', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
